version: "3"

tasks:
  dev:
    deps:
      - watch-standalone
      - watch-clientjs
    desc: Run cargo watch concurrently

  watch-standalone:
    desc: Start cargo watch
    dir: examples/standalone
    cmds:
      - mold -run cargo watch -x 'run -p standalone'

  watch-demo:
    desc: Start cargo watch
    dir: examples/demo
    cmds:
      - mold -run cargo watch -x run

  watch-standalone-release:
    desc: Start cargo watch
    cmds:
      - mold -run cargo watch -x 'run -p standalone --release'

  watch-standalone-systemfd:
    desc: Start cargo watch using systemfd to not drop connections on restart
    cmds:
      - systemfd --no-pid -s http::3000 -- mold -run cargo watch -x 'run -p standalone'

  watch-clientjs:
    desc: Build the client js bundle in watch mode
    dir: rhombus
    silent: true
    env:
      WATCH: true
    cmds:
      - node build.mjs
