version: "3"

tasks:
  dev:
    desc: Watch the standalone example
    dir: examples/standalone
    cmds:
      - mold -run cargo watch -x 'run -p standalone'

  apply:
    desc: Run rhombus-cli admin apply from examples/standalone/challenges
    dir: examples/standalone/challenges
    cmds:
      - mold -run cargo run --manifest-path ../../../Cargo.toml --bin rhombus-cli -- admin apply

  demo:
    desc: Watch the demo
    dir: examples/demo
    cmds:
      - mold -run cargo watch -x 'run -p demo'

  watch-standalone-systemfd:
    desc: Start cargo watch using systemfd to not drop connections on restart
    cmds:
      - systemfd --no-pid -s http::3000 -- mold -run cargo watch -x 'run -p standalone'
