[[language]]
name = "jinja"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
file-types = ["html"]
formatter = { command = "npx", args = ["prettier", "--parser", "jinja-template"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[language-server.deno-language-server]
command = "deno"
args = ["lsp"]

[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
language-servers = ["deno-language-server"]

[language-server.tailwindcss-ls]
config = { userLanguages = { jinja = "html" } }

[language-server.rust-analyzer.config]
diagnostics.disabled = ["inactive-code"]
rust-analyzer.cargo.features = ["all"]
