/// Code generated by tonic from the protobuf definitions
pub mod proto {
    pub const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("rhombus_descriptor");
    tonic::include_proto!("rhombus");
}
