# yaml-language-server: $schema=https://raw.githubusercontent.com/rhombusgg/rhombus/main/schema.json
title: Rhombus Demo
location_url: http://localhost:3000
database_url: file://rhombus.db
contact_email: admin@rhombus.gg
in_memory_cache: 20
start_time: 2024-09-04T03:14:00Z
# end_time: 2024-09-04T03:16:00Z
auth:
  - discord
  - email
  - ctftime
  - credentials
divisions:
  - name: Open
    description: Open division for everyone
    discord_role_id: 1297614892563435540
  - name: Undergraduate
    description: Undergraduate university students globally
    email_regex: ^.*.edu$
    requirement: Must verify a valid university .edu email address
    discord_role_id: 1297614961941680239
  - name: OSU
    description: OSU undergraduate students
    email_regex: ^.*\.\d+@(buckeyemail\.)?osu\.edu$
    requirement: Must verify a valid OSU email address. Max of up to 4 players
    max_players: 4
    discord_role_id: 1297615021773295709
discord:
  guild_id: 1160610137703186636
  client_id: 1160076447977848945
  author_role_id: 1198496803130183770
  first_blood_channel_id: 1295827879149703299
  support_channel_id: 1295827929359581337
  verified_role_id: 1170429782270431283
